### ISSUE TITLE
Wiki Todo

### ISSUE THREAD

**Issue by romankl** [romankl/snowstorm-server#1]
Required features:
- [x] Create new wikis
- [x] Delete wiki
- [x] Add pages to wiki 
- [x] Edit pages
  - [ ] Create a button to trigger it
- [x] Delete pages
  - [ ] Create a button to trigger it
- [ ] General markdown support
- [ ] Create wiki per repo
- [ ] Private/ public switch
- [ ] view my wikis/ wikis of other users
     - [ ] rewrite routes to include the user
- [ ] version handling
- [ ] refactoring 
- [ ] es indexing
