### ISSUE TITLE
User Todo

### ISSUE THREAD

**Issue by romankl** [romankl/snowstorm-server#3]
- [x] Provide login / signup
- [x] delete users
- [ ] disable users
- [ ] Profile page
- [ ] maybe avatars --> needs some rework
- [ ] update userprofile (passwd, username etc.)
- [x] switch wiki pages to user relevant
